### ISSUE TITLE
Implement CoinMate Ticker, Orderbook, and Trades

### ISSUE THREAD

**Issue by tmlee** [coingecko/cryptoexchange#146]

**Comment by rwhitworth** [comment]
I have a partial implementation of the ticker available here: https://github.com/rwhitworth/cryptoexchange/tree/coinmate

I am having trouble with generating the VCR cassette files.  Are the instructions in the contributing document accurate?

Here is the error I see:
```
rspec spec/exchanges/coinmate

An error occurred while loading ./spec/exchanges/coinmate.
Failure/Error: load file

LoadError:
  cannot load such file -- /Users/rwhitworth/Documents/git/cryptoexchange-rw/spec/exchanges/coinmate
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load_spec_file_handling_errors'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1494:in `block in load_spec_files'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `each'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `load_spec_files'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:100:in `setup'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/rwhitworth/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
# /Users/rwhitworth/.rbenv/versions/2.4.2/bin/rspec:23:in `load'
# /Users/rwhitworth/.rbenv/versions/2.4.2/bin/rspec:23:in `<main>'
#
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.
No examples found.

Finished in 0.00027 seconds (files took 0.15444 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by tmlee** [comment]
Thanks for your contribution @rwhitworth 
I left some comments over at your branch, looks good to me for Ticker API.

**Comment by rwhitworth** [comment]
I have updated the branch for the comments.  Thank you for taking the time to review.

I will start work on the Orderbook, but I will not be able to complete the Trades portion.  Should I PR now or after Orderbook is complete?

**Comment by tmlee** [comment]
Many thanks @rwhitworth Anything holding you back for the Trades? I am in the midst of getting the basics down https://github.com/coingecko/cryptoexchange/pull/147

**Comment by rwhitworth** [comment]
I will try to implement the trade API this weekend.  I see Gemini was added so I'll have an example to work from.

**Comment by tmlee** [comment]
@rwhitworth Sure, just wondering if it was a technical hurdle or something :)
